OPENAI_API_KEY = "sk-proj-SaZDx5VEflyUeu51uK0LT3BlbkFJOppl7UnFA8uCwaPYYlxe"
NEO4J_URL = "neo4j+s://3afee4ae.databases.neo4j.io"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = "sfdf8C5IhUMc7iO0_BbKxS2l58xpQLj_d9e9W8kTKSw"
